name: gen-ai
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  
  # Core Scientific Stack
  - numpy==1.26.4
  - pandas==2.2.0
  - scipy==1.12.0
  - ipython==8.21.0
  
  # Pip dependencies
  - pip
  - pip:
    - fal-client
    - requests==2.31.0
    - openpyxl==3.1.2
